### ISSUE TITLE
New development strategy

### ISSUE THREAD

**Issue by BenediktBurger** [pymeasure/pyleco#19]
As review time is scarce, but the code is quite stable (constant use in the lab), I propose the following development strategy with the following branches:

- `main` will contain the current development (what is now in the `development` branch)
- New changes will enter `main` via PRs
- `reviewed` will be a continuation of the current `main` branch, that is, reviewed by someone else than me.
- Eventually, `reviewed` will arrive at the head of `main`

What do you think @bilderbuchi , @bklebel ?

**Comment by bklebel** [comment]
That sounds quite reasonable to me. Also, in terms of package releases, this would make a bit more sense, since, as far as I understand, the current `main` would not properly work, as some parts are missing there. 
So, fine with me.

**Comment by BenediktBurger** [comment]
So it will help with #20

**Comment by BenediktBurger** [comment]
@bilderbuchi said in https://github.com/pymeasure/pyleco/pull/1#issuecomment-1611929886 that he supported a development in the main branch.
As he's not available at the moment, I'm merging #10.

**Comment by BenediktBurger** [comment]
Done
