### ISSUE TITLE
type hints?

### ISSUE THREAD

**Issue by bmoneke** [pymeasure/pyleco#2]
Are you open to use type hints in pyleco?

I know, in pymeasure we do not use type hints.

I played around with type hints (due to a seminar) and I liked the support of type checking.
As pyleco deals a lot with different types (lists, bytes, Messages...), type hinting and type checking can be powerful tools to support development.

The main idea behind type hints (in the signature) vs. hints in the docstring is, that docstring and code can diverge, while the type hint and code have to stay in tune (with a type checker).

With that, I'd like to use type hints.

**Comment by bilderbuchi** [comment]
Yes, I agree, :+1:.

**Comment by bklebel** [comment]
I agree too, when starting with a somewhat new code base, we might as well start off with new things the new python versions can offer, and type hints can definitely be quite helpful.

**Comment by bmoneke** [comment]
Ok, so that's agreed upon.
