### ISSUE TITLE
First (alpha) Release

### ISSUE THREAD

**Issue by BenediktBurger** [pymeasure/pyleco#20]
The code is stable and I'd like to make a release.

Can we release (with a major number of 0 indicating the not yet defined state of LECO) on pypi and conda?

ToDos:
- [x] install and run installed from test.pypi in empty environment.
- [x] Adjust Readme: #37 
- [x] #35 (fixed in #37)

Required PRs:
- #33
- #34 

Optional PRs:
- #32 for external contributions
- #30 for automatic publishing to pypi on github release.

**Comment by bklebel** [comment]
I am not sure about the actual current state, but understand that you are working with it in the lab already in a productive environment. As per your last comment in #19,  I understand that you would first change the development strategy, and move the (properly working) `development` branch to `main`, before releasing `main`, right? Sth like this sounds good to me.

The first release should definitely contain everything to start with a minimal setup, I think. This seems well to be the case. Ideally we would also have a bit more of a documentation than just the current readme and the example, however, I am not going to ask for things I cannot currently contribute myself, and I simply can't right now. I might be able to, in a few months though (once the thesis is written, as I hope). Until then, I don't want to block a first release, but I very much hope that the entry threshold for users would be considerably lowered. 
I know that we have quite an extensive docs-page for the protocol, but some "getting started" tutorial, which showcases the different elements, would be very nice indeed.

**Comment by BenediktBurger** [comment]
Yes, my idea was to ship the working version (current state of development).

I have been running my experiments with it, quite some time, now and it works without hassle.

Maybe I can add a more extensive "getting started" tutorial.

One idea for the release is, that it is simpler for people to install and to include in their code.

**Comment by BenediktBurger** [comment]
I added a getting started tutorial with some examples and some description, I hope it helps getting started.

**Comment by bklebel** [comment]
Thanks for the tutorial, this looks very nice! For a start, and to do a release, this is quite fine, I think. I made a small PR #24 -- once I have a bit more time, I would like to expand on it. For now, It would be fine with me to release.

**Comment by BenediktBurger** [comment]
Release is done and on pypi.

Installation on a new python installation (python 3.12) on a computer without previous python installation works. Also communication with my experiment network.

Deployment via script was nice.
