### ISSUE TITLE
CI code coverage fails on external PR

### ISSUE THREAD

**Issue by BenediktBurger** [pymeasure/pyleco#25]
In PR #24 , CI code coverage fails on the step creating a code coverage comment: https://github.com/pymeasure/pyleco/actions/runs/7687429088/job/20947438797?pr=24
It's job execution "#124"
~~~
Run MishaKav/pytest-coverage-comment@main
File read successfully "/home/runner/work/pyleco/pyleco/./pytest-coverage.txt"
Generating coverage report
File read successfully "/home/runner/work/pyleco/pyleco/./pytest.xml"
File read successfully "/home/runner/work/pyleco/pyleco/./pytest-coverage.txt"
Generating coverage report
File read successfully "/home/runner/work/pyleco/pyleco/./pytest.xml"
errors: 0
failures: 0
skipped: 5
tests: 577
time: 14.545
File read successfully "/home/runner/work/pyleco/pyleco/./pytest.xml"
./pytest-coverage.txt
  coverage: 85%
  color: green
  warnings: 5483
No previous comment found, creating a new one
Error: HttpError: Resource not accessible by integration
Error: Resource not accessible by integration
~~~

A stop gap measure could be to make the "code coverage comment" optional, such that the other steps (badge creation) are still executed.

**Comment by BenediktBurger** [comment]
Maybe it is a permissions issue, see the example https://github.com/MishaKav/pytest-coverage-comment/blob/main/.github/workflows/live-test.yml

**Comment by BenediktBurger** [comment]
@bklebel would you mind to open a PR with any change in order to test, whether the code coverage comment is generated as expected?
My PRs worked previously, but your PR did not, so maybe it was that permissions issue.

**Comment by bklebel** [comment]
sure, I now opened #27, with small changes to the `README.md`

**Comment by BenediktBurger** [comment]
Thanks.
It still fails.
According to https://github.com/peter-evans/create-or-update-comment#action-inputs it will always fail for pull requests from forks.
Funnily enough, it did not fail with my pull request (which is not in the fork) but failed after the merge.

**Comment by BenediktBurger** [comment]
Here's the main issue: https://github.com/MishaKav/pytest-coverage-comment/issues/68

**Comment by BenediktBurger** [comment]
In order to run the coverage after a merge, it is necessary to allow to write to contents (#29).

We have to find a way to allow these comments to prs from foreign forks.

**Comment by bklebel** [comment]
seems like you tracked it down. Do you want me to make another PR? Or is there something still unresolved?

**Comment by BenediktBurger** [comment]
I could reproduce it myself doing a PR from a branch in my personal fork (instead of from a branch in the pyleco repo).
I fixed only the failing run after a merge.

> We have to find a way to allow these comments to prs from foreign forks.

That is still open and I do not know the answer.
