### ISSUE TITLE
Setup automated tests

### ISSUE THREAD

**Issue by bmoneke** [pymeasure/pyleco#4]
Automated tests  would be good:

- [ ] code tests (running pytest)
- [ ] static code tests (mypy?)
- [ ] calculating test coverage
- [ ] linting (e.g. flake8)

**Comment by bilderbuchi** [comment]
:+1: 
In a new project, I would try out https://github.com/astral-sh/ruff as a linter.
Integrating coverage.py with pytest will not be a problem.
