### ISSUE TITLE
Harmonize, the capitalization -- PyLECO, PyLeco, pyleco,...

### ISSUE THREAD

**Issue by bmoneke** [pymeasure/pyleco#8]
Add some point we should decide on, and harmonize, the capitalization -- PyLECO, PyLeco, pyleco,...

_Originally posted by @bilderbuchi in https://github.com/pymeasure/pyleco/pull/7#discussion_r1271270446_

as the original name is `LECO`, PyLECO is a strong candidate.

PyLeco is like a Python class in CamelCase.

For consistency in naming within the LECO universe, I'm for PyLECO

ToDo:

- [x] rename Repository (shown name, not URL)
- [x] rename readme
- [x] rename all files

**Comment by bilderbuchi** [comment]
To note, we don't gave to be 100% consistent -- the package name could easily be lower case pyleco, that seems common enough. But in text/docs, it would be good to choose one way and stick with it.

**Comment by bmoneke** [comment]
I'm for a lower case python package name (pyleco), but in the docs etc. I prefer the aforementioned spelling. 

Am 23. Juli 2023 09:55:43 MESZ schrieb Christoph Buchner ***@***.***>:

**Comment by bilderbuchi** [comment]
Agreed on both points.

**Comment by bmoneke** [comment]
So:
Package name (for imports etc.): `pyleco`
Human name of the project (in docs etc.) : `PyLECO`
